# Generated by Django 5.1.6 on 2025-02-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('html_url', models.CharField(max_length=150)),
            ],
        ),
    ]
