# Generated by Django 5.1.6 on 2025-04-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userdata_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=150, unique=True)),
                ('html_url', models.URLField()),
                ('repos_url', models.URLField()),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
