# Generated by Django 5.1.6 on 2025-04-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userinfo_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_type',
            field=models.CharField(max_length=200),
        ),
    ]
